// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProgramDesigner.Api.Data;

#nullable disable

namespace ProgramDesigner.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718152555_AddCreatedAtToPrograms")]
    partial class AddCreatedAtToPrograms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.LearningProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RootGroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RootGroupId");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.MissingPrerequisiteRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MissingPrerequisiteTemplateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MissingPrerequisites");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ParentGroupId")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Nodes", (string)null);

                    b.HasDiscriminator<string>("NodeType").HasValue("Node");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.NodePrerequisite", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("text");

                    b.Property<string>("PrerequisiteId")
                        .HasColumnType("text");

                    b.Property<string>("PrerequisiteTemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("NodeId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("PrerequisiteTemplateId");

                    b.ToTable("NodePrerequisites", (string)null);
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Group", b =>
                {
                    b.HasBaseType("ProgramDesigner.Api.Domain.Entities.Node");

                    b.Property<int>("GroupType")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredSelections")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Step", b =>
                {
                    b.HasBaseType("ProgramDesigner.Api.Domain.Entities.Node");

                    b.HasDiscriminator().HasValue("Step");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.LearningProgram", b =>
                {
                    b.HasOne("ProgramDesigner.Api.Domain.Entities.Group", "RootGroup")
                        .WithMany()
                        .HasForeignKey("RootGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RootGroup");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Node", b =>
                {
                    b.HasOne("ProgramDesigner.Api.Domain.Entities.Group", "ParentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.NodePrerequisite", b =>
                {
                    b.HasOne("ProgramDesigner.Api.Domain.Entities.Node", "Node")
                        .WithMany("Prerequisites")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgramDesigner.Api.Domain.Entities.Node", "Prerequisite")
                        .WithMany("RequiredBy")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Node", b =>
                {
                    b.Navigation("Prerequisites");

                    b.Navigation("RequiredBy");
                });

            modelBuilder.Entity("ProgramDesigner.Api.Domain.Entities.Group", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
